In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

/Users/happiness/opt/anaconda3/envs/dl-playground/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# a simple MLP with 2 hidden layers and ReLU activation
class MLP(nn.Module):
    def __init__(self, in_feat=2, out_feat=3, W=256):
        super().__init__()
        self.fc1 = nn.Linear(in_feat, W)
        self.fc2 = nn.Linear(W, W)
        self.fc3 = nn.Linear(W, out_feat)
    
    def forward(self, input):
        x = F.relu(self.fc1(input))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [5]:
model = MLP()
for p in model.parameters():
    print(p.shape)

torch.Size([256, 2])
torch.Size([256])
torch.Size([256, 256])
torch.Size([256])
torch.Size([3, 256])
torch.Size([3])


In [18]:
x = torch.randn(2, 2)
print(x)
print(torch.max(x))
print(torch.max(x, dim=-1)[0])

tensor([[-0.0171,  0.7549],
        [-0.1421,  1.3371]])
tensor(1.3371)
tensor([0.7549, 1.3371])


# Repeat

In [6]:
x = torch.tensor([1, 2, 3])
x = x.repeat(1, 2)
x.shape

torch.Size([1, 6])

# Slicing

In [50]:
# Syntax: tensor[tensor_position_start:tensor_position_end, tensor_dimension_start:tensor_dimension_end , tensor_value_start:tensor_value_end]
# so basically tensor[:, :, 1] means take all the first values in the 3rd dimension
# tensor[:, :, 1] is equivalent to tensor[:, :, 0:1] in value, but not in shape

x = torch.arange(1, 28).reshape(3, 3, -1)
print(x)
x[:, :, 1].shape, x[:, :, 0:1].shape, x[:, :, 0:1].squeeze(-1).shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])


tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])

# Forwarding

In [61]:
layer = nn.Linear(2, 3)
x = torch.randn(2, 2)
layer(x).shape

torch.Size([2, 3])